### PR TITLE
Countdown Implemented As Per Assignment

### PR DESCRIPTION
**Pull request by mustafaazad03**
**Pull Request Title:**
Improved some UI and Implemented Timer Component.

**Changes Made:**
- Implemented Timer Component.
- Enhanced UI.

**Screenshots:**
image

**Code Review:**
I would appreciate a review from a team member to ensure code quality and best practices.

@priyaljain919 @Atharv-110 .

### CODE REVIEW

**Comment by Atharv-110** [comment]
@mustafaazad03 can you please attach a screenshot for mobile responsive.

**Comment by priyaljain919** [comment]
Hi @mustafaazad03, you did great work but we need to place it on after hero component not inside hero component or any other component.

As this timer component should be an independent component please do the fixes and push your changes.

And timer component should be come after hero component differently.

Cc @Atharv-110

**Comment by mustafaazad03** [comment]
ok sure

**Comment by mustafaazad03** [comment]
image

Hi @priyaljain919 ,
Will this works ??

**Comment by mustafaazad03** [comment]
Or after book your ticket

**Comment by priyaljain919** [comment]
Sure works!
Please give us some time to review the changes and we will get back to you by Monday. 

Thanks for the contribution.

**Comment by mustafaazad03** [comment]
Sure mam

**Comment by priyaljain919** [comment]
@mustafaazad03 we will get back to you in 1-2 days shortly for upcoming things. Please do not raise the PR for further tasks we can't merge scrolling PR as we need to keep our website in simple way. 

Please let us know if you have any questions or concerns 

Cc @Atharv-110

**Comment by mustafaazad03** [comment]
Ok No problem.

**Pull request closed without merging**
